server:
  port: 8084

spring:
  application:
    name: oscms-material-service
  
  # 数据库配置 - 资料数据库
  datasource:
    url: jdbc:mysql://localhost:3306/oscms_material_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:760810abcd..}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # Flyway 数据库迁移
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Eureka 客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 日志配置
logging:
  level:
    com.osc.oscms: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Knife4j 文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn

# 文件存储配置
file:
  storage:
    path: ${FILE_STORAGE_PATH:./uploads/materials/}
    base-url: ${FILE_BASE_URL:http://localhost:8084/files/}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTGenerationWhichIsVeryLongAndSecure12345!}
  expiration:
    ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour

---
spring:
  config:
    activate:
      on-profile: k8s
  application:
    name: oscms-material-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA Configuration for K8s
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    
  # File upload configuration for K8s
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Server Configuration for K8s
server:
  port: 8084

# Eureka Client Configuration for K8s
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: true

# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.osc.oscms.materialservice.domain
  configuration:
    map-underscore-to-camel-case: true

# File storage configuration for K8s
file:
  storage:
    path: ${FILE_STORAGE_PATH:/app/uploads/materials/}
    base-url: ${FILE_BASE_URL:http://oscms-material-service:8084/files/}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTGenerationWhichIsVeryLongAndSecure12345!}
  expiration:
    ms: ${JWT_EXPIRATION_MS:3600000}

# Logging
logging:
  level:
    com.osc.oscms.materialservice: INFO